---
title: "Testing Shiny Plots"
author: "Sean Kent"
date: "3/25/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# library(shiny)
library(tidyverse)
library(sf)
library(maps)
library(plotly)
library(here)
library(ggrepel)

```

```{r}

wi_timeseries <- 
  read.csv("data/timeseries-tidy.csv") %>% 
  filter(state == "WI") %>% 
  as_tibble() %>% 
  pivot_wider(names_from = "type", 
              values_from = "value") %>% 
  # adjust county name to match maps data
  mutate(
    county2 = county %>% 
      str_remove(" County") %>% 
      str_remove_all("\\.") %>% 
      str_to_lower(),
    date = as.Date(date)
  )

wi_county <- 
  maps::map("county", plot = FALSE, fill = TRUE) %>% 
  st_as_sf() %>% 
  subset(grepl("wisconsin", .$ID)) %>% 
  mutate(county = str_replace(ID, "wisconsin,", ""))
```




```{r}
wi_timeseries
```


## Align x-axis to days since 10 cases

```{r}
counties_to_plot <- c("Dane County", "Milwaukee County", "Waukesha County", "Fond du Lac County")
# counties_to_plot <- input$counties_to_plot


wi_timeseries %>% 
  filter(county %in% counties_to_plot) %>% 
  group_by(county, state) %>% 
  filter(cases >= 10) %>% 
  arrange(county, state, date) %>% 
  mutate(days_since_cases = row_number()) %>% 
  ungroup() %>% 
  ggplot(aes(days_since_cases, cases)) +
  geom_line(aes(color = county), size = 1.5) +
  scale_x_continuous(breaks = seq(1,21,by = 2), expand = c(0.06,0,0.06,2)) +
  # scale_x_date(limits = c(Sys.Date() - 14, NA), expand = c(0.06,0,0.06,2),
  #              date_breaks = "2 days", date_labels = "%b %d") +
  labs(
    title = "County Level Wisconsin Cases of COVID-19 (last 2 weeks)",
    y = "Cases",
    x = "Days since 10 cases"
  ) +
  theme_minimal() +
  theme(legend.position = "none") +
  geom_label_repel(aes(label = county),
                     data = . %>% filter(date == max(wi_timeseries$date)),
                     nudge_x = 2,
                     nudge_y = 5
    )
```


```{r}
p <- 
  wi_timeseries %>%
  filter(county %in% counties_to_plot) %>%
  ggplot(aes(date, cases)) +
  geom_line(aes(color = county), size = 1.5) +
  scale_x_date(limits = c(Sys.Date() - 14, NA), expand = c(0.06,0,0.06,2),
               date_breaks = "2 days", date_labels = "%b %d") +
  labs(
    title = "County Level Wisconsin Cases of COVID-19 (last 2 weeks)",
    y = "Cases",
    x = NULL
  ) +
  theme_minimal() +
  theme(legend.position = "none")


p

if(input$logscale) {
  p <- p +
    scale_y_log10() +
    geom_label_repel(aes(label = county),
                     data = . %>% filter(date == max(wi_timeseries$date)),
                     nudge_x = 2
    )
} else {
  p <- p + 
    geom_label_repel(aes(label = county),
                     data = . %>% filter(date == max(wi_timeseries$date)),
                     nudge_x = 2,
                     nudge_y = 5
    )
}

p
```





